### ISSUE TITLE
Github action failing when only cloudflare keys set

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/cxe2stix_helper#6]
https://github.com/muchdogesec/cxe2stix_helper?tab=readme-ov-file#option-1-use-cloudflare_-vars

https://github.com/muchdogesec/cxe2stix_helper/actions/runs/10555202078

Should be possible to run with just cloudflare keys

![image](https://github.com/user-attachments/assets/376e2811-55d0-4bb9-b9f2-8a2361aeee09)

**Comment by himynamesdave** [comment]
still failing, looks like error in path

https://github.com/muchdogesec/cxe2stix_helper/actions/runs/10591840316/job/29350011781

Also, can you make the CRON_TIME a variable in the action? This way it'll be possible to test by changing run time without having to modify the code

**Comment by fqrious** [comment]
> still failing, looks like error in path

I didn't configure it to checkout submodules, fixed

> Also, can you make the CRON_TIME a variable in the action? This way it'll be possible to test by changing run time without having to modify the code

[Not supported](https://github.com/orgs/community/discussions/25928)

**Comment by himynamesdave** [comment]
now failing here:

```
Run source cxe2stix_helper-venv/bin/activate
["--run_cpe2stix", "--run_cve2stix", "--last_modified_earliest", "2024-08-28T00:00:00", "--last_modified_latest", "2024-08-28T23:59:59", "--file_time_range", "1d"]
2024-08-29 07:06:44,265 | ERROR | cannot import name 'Never' from 'typing' (/usr/lib/python3.10/typing.py)
Traceback (most recent call last):
  File "/home/runner/work/cxe2stix_helper/cxe2stix_helper/cxe2stix_helper.py", line 197, in <module>
    main()
  File "/home/runner/work/cxe2stix_helper/cxe2stix_helper/cxe2stix_helper.py", line 110, in main
    import cve2stix.main as cve2stix
  File "/home/runner/work/cxe2stix_helper/cxe2stix_helper/cve2stix/cve2stix/main.py", line [15](https://github.com/muchdogesec/cxe2stix_helper/actions/runs/10610328764/job/29407604905#step:9:16), in <module>
    from .parse_api_response import parse_cve_api_response
  File "/home/runner/work/cxe2stix_helper/cxe2stix_helper/cve2stix/cve2stix/parse_api_response.py", line 9, in <module>
    from typing import List, Never
ImportError: cannot import name 'Never' from 'typing' (/usr/lib/python3.10/typing.py)
2024-08-29 07:06:44,265 | ERROR | cannot import name 'Never' from 'typing' (/usr/lib/python3.10/typing.py)
Traceback (most recent call last):
  File "/home/runner/work/cxe2stix_helper/cxe2stix_helper/cxe2stix_helper.py", line [19](https://github.com/muchdogesec/cxe2stix_helper/actions/runs/10610328764/job/29407604905#step:9:20)7, in <module>
    main()
  File "/home/runner/work/cxe2stix_helper/cxe2stix_helper/cxe2stix_helper.py", line 110, in main
    import cve2stix.main as cve2stix
  File "/home/runner/work/cxe2stix_helper/cxe2stix_helper/cve2stix/cve2stix/main.py", line 15, in <module>
    from .parse_api_response import parse_cve_api_response
  File "/home/runner/work/cxe2stix_helper/cxe2stix_helper/cve2stix/cve2stix/parse_api_response.py", line 9, in <module>
    from typing import List, Never
ImportError: cannot import name 'Never' from 'typing' (/usr/lib/python3.10/typing.py)
[20](https://github.com/muchdogesec/cxe2stix_helper/actions/runs/10610328764/job/29407604905#step:9:21)24-08-29 07:06:44,266 | INFO | Killing all child processes
2024-08-29 07:06:44,266 | INFO | Killing all child processes
```

https://github.com/muchdogesec/cxe2stix_helper/actions/runs/10610328764/job/29407604905

**Comment by himynamesdave** [comment]
@fqrious still failing at same step since 44e94d3

**Comment by fqrious** [comment]
fixed in #10

**Comment by himynamesdave** [comment]
@fqrious since the above updates, the script is still failing

**Comment by fqrious** [comment]
send log

**Comment by himynamesdave** [comment]
can you see the runs here @fqrious ?

https://github.com/muchdogesec/cxe2stix_helper/actions/workflows/daily-r2.yml

These contain the logs

**Comment by fqrious** [comment]
you have not set `NVD_API_KEY` in secrets

![Image](https://github.com/user-attachments/assets/74c3c99d-8e5a-4b97-9900-71f8b4e9d6da)
